title:        API Evangelist History of APIs
description: This is a walk through on the history of web APIs, highlighting some of the pioneers who have made the API space what it is.
url:          history.apievangelist.com
raw_url: history.apievangelist.com/apis/

tag: History of APIs

logo:         https://s3.amazonaws.com/kinlane-productions2/api-evangelist/api-evangelist-logo-lessons.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

github_user: api-evangelist-api-consumer-lessons
github_repo: history
github_branch: master

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions2/footer/empowered-by-you-banner.png
footer_image_width: 60
